// BASELINE — what a model writes with no skill loaded.
//
// Generated by Claude Sonnet, prompt:
//   "Write a SwiftUI view for an iOS 18 app: a list of crypto assets
//    (name, symbol, balance, USD value) where tapping an asset navigates to a
//    detail view showing that asset's balance and a placeholder chart."
//
// Unedited except for trimming the model, sample data, and chart, which are
// identical in both versions and not what this comparison is about.
//
// This is competent code. It is also undesigned: the detail view has no
// relationship to the row that produced it.

import SwiftUI

struct AssetListView: View {
    let assets: [CryptoAsset] = CryptoAsset.sampleAssets

    var totalUSDValue: Double {
        assets.reduce(0) { $0 + $1.usdValue }
    }

    var body: some View {
        NavigationStack {
            List {
                Section {
                    VStack(alignment: .leading, spacing: 4) {
                        Text("Total Balance")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                        Text(totalUSDValue.formatted(.currency(code: "USD")))
                            .font(.largeTitle.bold())
                    }
                    .padding(.vertical, 8)
                }

                Section("Assets") {
                    ForEach(assets) { asset in
                        NavigationLink(value: asset) {
                            AssetRow(asset: asset)
                        }
                    }
                }
            }
            .navigationTitle("Portfolio")
            .navigationDestination(for: CryptoAsset.self) { asset in
                AssetDetailView(asset: asset)
            }
        }
    }
}

struct AssetDetailView: View {
    let asset: CryptoAsset

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 24) {
                VStack(alignment: .leading, spacing: 8) {
                    Text(asset.name)
                        .font(.title2.bold())
                    Text(asset.symbol)
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                }

                VStack(alignment: .leading, spacing: 4) {
                    Text("Balance")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    Text("\(asset.formattedBalance) \(asset.symbol)")
                        .font(.title.bold())
                    Text(asset.formattedUSDValue)
                        .font(.headline)
                        .foregroundStyle(.secondary)
                }
                .padding()
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(.thinMaterial, in: RoundedRectangle(cornerRadius: 16))

                PriceChart(asset: asset)
            }
            .padding()
        }
        .navigationTitle(asset.symbol)
        .navigationBarTitleDisplayMode(.inline)
    }
}

// No @Namespace.
// No matchedTransitionSource.
// No navigationTransition.
// No animation of any kind.
// No Reduce Motion handling.
// Every value change is instant.
